[package]
name = "relayer"
version = "0.1.0"
edition = "2024"

[dependencies]
ethers = { version = "2", features = ["abigen", "ws", "rustls"] }
tokio = { version = "1", features = ["full"] }
dotenvy = "0.15"
anyhow = "1.0"
